version: 2
jobs:
  build:
    docker:
      - image: centos:7
    steps:
      - run: yum install centos-release-scl epel-release -y
      - run: yum install git cmake3 devtoolset-4-gcc* hwloc-devel libmicrohttpd-devel openssl-devel make -y
      - checkout
      - run: source /opt/rh/devtoolset-4/enable
      - run: pwd
      - run: ls -la
      - run: cmake3 . -DCMAKE_BUILD_TYPE=Release -DXMR-STAK_CURRENCY=monero -DCPU_ENABLE=enable || true
      - run: cd project && cmake3 . -DCMAKE_BUILD_TYPE=Release -DXMR-STAK_CURRENCY=monero -DCPU_ENABLE=enable || true
      - run: make install
      - run: cd ..