version: 2
jobs:
  build:
    docker:
      - image: fedora:27
    steps:
      - run: dnf install gcc gcc-c++ hwloc-devel libmicrohttpd-devel libstdc++-static make openssl-devel cmake -y
      - run: gcc -v
      - checkout
      - run: cmake3 . -DCMAKE_BUILD_TYPE=Release -DXMR-STAK_CURRENCY=monero -DCPU_ENABLE=enable || true
      - run: make install
      - run: ls -la
      - run: pwd
